### ISSUE TITLE
Moving concs_table_png_data to another file

### ISSUE THREAD

**Issue by Utopiah** [scrtwpns/pigment-mixing#3]
Arguably `concs_table_png_data` is data rather than code. Beside the inability to preview the code, and thus discuss it, here on Github it makes the main file go from 10MB to 76KB which for some editors might also make it challenging to parse. If it doesn't impact performances particularly I'd suggest moving it to a dedicated file.

**Comment by virtualritz** [comment]
Just do it and open a PR? :)

**Comment by MaxBittker** [comment]
respectfully, I was shocked that the data required was so large. Can anyone help me understand why?

**Comment by virtualritz** [comment]
Just read the paper. They bake some computations into a lookup table which is stored in-line as a PNG. This is a requirement to make the mixing computations fast enough for realtime applications.

I would dare think this may not be hold true if compute shaders or SIMD optimized CPU code would be used to do them though.

In any case I think it would be great if the code to generate the LO table could be published too.

So one could opt to run that code on application startup with a one-time runtime penalty instead of having to add 50MB to any binary using `pigment-mixing`.

My gut feeling is that generating the LO table (in parallel) would not incur a notable delay on a modern 8- or 16 core desktop machine.

**Comment by scrtwpns** [comment]
The reason for inlining the lookup table in code is to make Mixbox as easy to integrate into the host software as possible. 

Requiring a separate initialization step to load the table from filesystem would make things unnecessarily more complex. Even though the table occupies 10 MB in code, the actual footprint in compiled binary is only 4 MB. Therefore, we keep the table inlined and won't recompute it at runtime.

However, we have added a separate PNG file with the lookup table for users who prefer to load it as a texture to access it from shaders.

**Comment by virtualritz** [comment]
What about generating the table on the fly? What is the issue with that?
